CyclomaticComplexity:
  Max: 8
MethodLength:
  Max: 30
ClassLength:
  Max: 320
ClassVars:
  Enabled: false
BlockLength:
  Enabled: false
ConditionalAssignment:
  Enabled: false
PerceivedComplexity:
  Max: 10
AbcSize:
  Max: 41
