sudo: false
language: ruby
before_install: gem install bundler
branches:
  only:
    - master
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

script:
  - bundle exec rake rubocop
  - bundle exec rake spec

matrix:
  allow_failures:
  - rvm: 2.3.7
